### ISSUE TITLE
Milestone #1: MVP

### ISSUE THREAD

**Issue by shimks** [Wishbone-Deli/wishbonedeli.ca#1]
## Description
The goal of this milestone is to get a minimum functional web application running to replace the old website, while applying foundational settings applied (such as React for offsite queries, state management, and deployment via containers) to keep the web application scalable.

## Major issues
- [ ] Create a docker container that uses Express.js to serve the application
- [ ] Create a barebone index.html with TypeScript, React, Webpack, ESLint, and prettier configured
- [ ] Create Router with skeletal pages for navigation panel, closed notices, home, catering menu, dine-in menu, contact us, and the footer as well as naming them
- [ ] Create the header
- [ ] Create the footer
- [ ] Create the homepage
- [ ] Create the contact us page
  - should almost be a copy of the contact form in the homepage; details are not set in stone
- [ ] Create the create the catering menu page
- [ ] Create the dine-in menu page
- [ ] Create styling via scss

It's noted that all features are accompanied by tests.

- NOTE: the complete planning for this milestone is incomplete and its various goals are subjected to change with finer or coarser scoping.
